# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.1

# Select what we should cache between builds
cache:
  paths:
  - vendor/
  - $HOME/.composer/cache

stages:
  - test
  - production

test-php:
  services:
    - node:9.11
    - php:7.1
    - mysql:5.7
  stage: test
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - build/
    expire_in: 3 days
  before_script:
    - export CFP_ENV=testing
    - apt-get update -yqq
    - apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
    # Install PHP extensions
    - docker-php-ext-install mbstring mcrypt pdo_mysql curl json intl gd xml zip bz2 opcache
    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    # Install deployer
    - curl -LO https://deployer.org/deployer.phar
    - echo "prepare build"
    - php composer.phar validate --no-check-publish
    - php composer.phar install
    - sh .travis/setup-mail.sh
    - cp config/${CFP_ENV}.yml.dist config/${CFP_ENV}.yml
    - php vendor/bin/phinx migrate --environment ${CFP_ENV}
  script:
    - echo "Run PHP tests"
    - vendor/bin/phpunit --testsuite integration

test-js:
  image: node:9.11
  stage: test
  script:
    - echo "Run frontend tests"
    - npm install
    - npm run production

to-production:
  when: manual
  stage: production
  services:
    - node:9.11
    - php:7.1
  before_script:
  before_script:
    #- apt-get update -yqq
    #- apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
    # Install PHP extensions
    #- docker-php-ext-install mbstring mcrypt pdo_mysql curl json intl gd xml zip bz2 opcache
    # Install and run Composer
    - curl -sS https://getcomposer.org/installer | php
    # Install deployer
    - curl -LO https://deployer.org/deployer.phar | php
    - php composer.phar install --no-dev --optimize-autoloader
    - php bin/console cache:clear --env=${CFP_ENV}
    - php bin/console cache:warmup -env=${CFP_ENV}
    - npm install
  when: manual
  script:
    - echo "Deploy to the first available ${CFP_ENV} server"
    - php deployment.phar deployment.ini

services:
  - node:9.11
  - php:7.1
  - mysql:5.7

variables:
  MYSQL_DATABASE: cfp_test
  MYSQL_ROOT_PASSWORD: ROOT
  MYSQL_PASSWORD: gitlab
  MYSQL_USER: gitlab
